export const LOGIN_UPDATE = 'LOGIN_UPDATE'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const REGISTER_UPDATE = 'REGISTER_UPDATE'
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCEED = 'REGISTER_SUCCEED'
export const REGISTER_FAILED = 'REGISTER_FAILED'

export const GET_VERIFICATE_CODE_REQUEST = 'GET_VERIFICATE_CODE_REQUEST'
export const GET_VERIFICATE_CODE_SUCCEED = 'GET_VERIFICATE_CODE_SUCCEED'
export const GET_VERIFICATE_CODE_FAILED = 'GET_VERIFICATE_CODE_FAILED'

export const CHECK_VERIFICATE_CODE_REQUEST = 'CHECK_VERIFICATE_CODE_REQUEST'
export const CHECK_VERIFICATE_CODE_SUCCEED = 'CHECK_VERIFICATE_CODE_SUCCEED'
export const CHECK_VERIFICATE_CODE_FAILED = 'CHECK_VERIFICATE_CODE_FAILED'

export const RESET_PASSWORD_UPDATE = 'RESETPASSWORD_UPDATE'
export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCEED = 'RESETPASSWORD_SUCCEED'
export const RESET_PASSWORD_FAILED = 'RESETPASSWORD_FAILED'

export const USERINFO_UPDATE = 'USERINFO_UPDATE'
export const USERINFO_REQUEST = 'USERINFO_REQUEST'
export const USERINFO_SUCCEED = 'USERINFO_SUCCEED'
export const USERINFO_FAILED = 'USERINFO_FAILED'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCEED = 'LOGOUT_SUCCEED'
export const LOGOUT_FAILED = 'LOGOUT_FAILED'

export const PASSWORD_UPDATE = 'PASSWORD_UPDATE'
export const PASSWORD_REQUEST = 'PASSWORD_REQUEST'
export const PASSWORD_SUCCEED = 'PASSWORD_SUCCEED'
export const PASSWORD_FAILED = 'PASSWORD_FAILED'

export const FIND_BANNERS_REQUEST = 'FIND_BANNERS_REQUEST'
export const FIND_BANNERS_SUCCEED = 'FIND_BANNERS_SUCCEED'
export const FIND_BANNERS_FAILED = 'FIND_BANNERS_FAILED'

export const BANNERS_ADD_UPDATE = 'BANNERS_ADD_UPDATE'
export const BANNERS_ADD_REQUEST = 'BANNERS_ADD_REQUEST'
export const BANNERS_ADD_SUCCEED = 'BANNERS_ADD_SUCCEED'
export const BANNERS_ADD_FAILED = 'BANNERS_ADD_FAILED'

export const IMG_HASH_SUCCEED = 'IMG_HASH_SUCCEED'
export const IMG_HASH_FAILED = 'IMG_HASH_FAILED'
