export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED'
export const LOGIN_FAILED = 'LOGIN_FAILED'
export const UPDATE_USER = 'UPDATE_USER'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCEED = 'REGISTER_SUCCEED'
export const REGISTER_FAILED = 'REGISTER_FAILED'
export const REGISTER_UPDATE = 'REGISTER_UPDATE'

export const GETCODE = 'GETCODE'
export const GETCODE_SUCCEED = 'GETCODE_SUCCEED'
export const GETCODE_FAILED = 'GETCODE_FAILED'
