# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "每日构建到 fir.im"
  lane :fir do
    # add actions here: https://docs.fastlane.tools/actions
    disable_automatic_code_signing(path: "tok.xcodeproj")

    # today = Time.now.strftime("%Y-%m-%d")
    time_stamp = Time.now.strftime("%Y-%m-%d %H:%M:%S")
    release_log = '由勤劳的机器人构建于' + time_stamp
    
    build_ios_app(
      project: "tok.xcodeproj",
      scheme: "tok",
      export_options: {
        method: "ad-hoc",
        provisioningProfiles: { 
          "cn.d3j.test": "tok-adhoc",
        }
      }
    )
    
    sh("fir", "publish", "-c", release_log, '../tok.ipa')
  end
end
